# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               'mlampros'
tagline:             'My Blog'
description:         ''
url:                 mlampros.github.io
baseurl:             '/'
# Use paginate to set the number of pages shown
paginate:            5

excerpt_separator: '<br>'

author:
  name: 'Mouselimis Lampros'
  github: mlampros
  email_md5: abe1a64ce1807f540ca9deeebdf47820
  google_analytics_id: UA-72555431-1
  google_analytics_url: mlampros.github.io

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/mlampros
  messages:       https://github.com/mlampros/mlampros_github_io_messages/issues/new
