# TODO: add redcarpet extensions when becomming comfortable with markdown
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

# Permalinks
permalink:           pretty

# Setup
title:               'mlampros'
tagline:             'Organizing and Sharing thoughts, Receiving constructive feedback'
description:         ''
url:                 mlampros.github.io
baseurl:             '/'
# Use paginate to set the number of pages shown
paginate:            5

excerpt_separator: '<br>'

author:
  name: 'Mouselimis Lampros'
  github: mlampros
  email: mouselimislampros@gmail.com
  google_analytics_id: UA-72555431-1
  google_analytics_url: mlampros.github.io

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/mlampros
