# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               mlampros
tagline:             'My Blog'
description:         ''
url:                 mlampros.github.io
baseurl:             ''
# Use paginate to set the number of pages shown
paginate:            5
name:                Mouselimis Lampros
email:               mouselimislampros@gmail.com

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/poole/lanyon
